format = '''
$battery$all$character'''

[character]
format = '$symbol '
success_symbol = "[:](bold white)"
error_symbol = "[!](bold red)"
vimcmd_symbol = "[<](bold green)"

[battery]
format = '[$symbol]($style) '
full_symbol = '󰁹'
charging_symbol = '󰂄'
discharging_symbol = '󰂌'

[[battery.display]]
threshold = 10
style = 'bold #ff0000'
charging_symbol = '󰁺󱐋'
discharging_symbol = '󰁺'

[[battery.display]]
threshold = 20
style = 'bold #ff3300'
charging_symbol = '󰁻󱐋'
discharging_symbol = '󰁻'

[[battery.display]]
threshold = 30
style = 'bold #ff6600'
charging_symbol = '󰁼󱐋'
discharging_symbol = '󰁻'

[[battery.display]]
threshold = 40
style = 'bold #ff9900'
charging_symbol = '󰁽󱐋'
discharging_symbol = '󰁽'

[[battery.display]]
threshold = 50 
style = 'bold #ffcc00'
charging_symbol = '󰁾󱐋'
discharging_symbol = '󰁾'

[[battery.display]]
threshold = 60
style = 'bold #ffff00'
charging_symbol = '󰁿󱐋'
discharging_symbol = '󰁿'

[[battery.display]]
threshold = 70
style = 'bold #ccff00'
charging_symbol = '󰂀󱐋'
discharging_symbol = '󰁿'

[[battery.display]]
threshold = 80
style = 'bold #99ff00'
charging_symbol = '󰂁󱐋'
discharging_symbol = '󰂁'

[[battery.display]]
threshold = 90
style = 'bold #66ff00'
charging_symbol = '󰂂󱐋'
discharging_symbol = '󰂂'

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "

[azure]
symbol = "az "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "
style = 'blue bold'

[raku]
symbol = "raku "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "

